// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xucnzmzhcqyibgfldfkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Y256bXpoY3F5aWJnZmxkZmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDYzODIsImV4cCI6MjA3MDAyMjM4Mn0.lzwUfAYqlsNwsZpZwVeqDQEevg82xSRTePs9TdWEtI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});